In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience.fillna('zero',inplace=True)
df.experience = [w2n.word_to_num(i) for i in list(df['experience'])]
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [4]:
median_test_score = df['test_score(out of 10)'].median()
df['test_score(out of 10)'].fillna(median_test_score,inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [7]:
model.intercept_

17737.26346433768

In [8]:
model.predict([[2,9,6]])

array([53205.96797671])

In [9]:
model.predict([[12,10,10]])

array([92002.18340611])

# How to save a model

In [13]:
import pickle as pk

In [14]:
with open('model_pickle','wb') as f:
    pk.dump(model,f)

In [15]:
with open('model_pickle','rb') as f:
    imported_model = pk.load(f)

In [16]:
imported_model.predict([[15,10,10]])

array([100441.04803493])

In [18]:
import joblib

In [20]:
with open('model_joblib','wb') as f:
   joblib.dump(model,f) 

In [23]:
with open('model_joblib','rb') as f:
    imported_joblib_model = joblib.load('model_joblib')

In [24]:
imported_joblib_model.predict([[15,10,10]])

array([100441.04803493])